# Generated by Django 4.2 on 2023-05-05 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Objet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('url_photo', models.URLField(blank=True, null=True)),
                ('description', models.CharField(max_length=500, null=True)),
                ('prix_jour', models.DecimalField(decimal_places=2, max_digits=5)),
                ('caution', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tag', models.CharField(choices=[('O', 'Outil'), ('F', 'Film'), ('L', 'Livre'), ('J', 'Jeu'), ('IF', 'Informatique'), ('V', 'Vehicule'), ('MO', 'Mode'), ('IM', 'Immobilier'), ('MU', 'Musique'), ('A', 'Autre')], max_length=5)),
            ],
        ),
    ]
