# Generated by Django 4.2 on 2023-05-09 08:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_objet_date_creation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objet',
            name='date_creation',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='date_creation',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='mail',
            field=models.EmailField(max_length=50),
        ),
    ]
