# Generated by Django 4.2 on 2023-05-09 12:24

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_alter_objet_date_creation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abonnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_achat', models.DateField(auto_now_add=True)),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Avis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('commentaire', models.CharField(blank=True, max_length=200, null=True)),
                ('note', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2023, 5, 9)), django.core.validators.MaxValueValidator(datetime.date(2023, 8, 17))])),
                ('date_fin', models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2023, 5, 9)), django.core.validators.MaxValueValidator(datetime.date(2023, 8, 17))])),
                ('date_fin_reelle', models.DateField(blank=True, null=True)),
                ('valide', models.BooleanField(default=False)),
                ('payee', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Signalement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('type_signalement', models.CharField(choices=[('D', 'Defectueux'), ('V', 'Vulgarite'), ('R', 'Retard'), ('P', 'Paiement')], max_length=5)),
                ('commentaire', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='objet',
            name='date_creation',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='objet',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='date_creation',
            field=models.DateField(auto_now_add=True),
        ),
    ]
