# Generated by Django 4.2 on 2023-05-09 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_abonnement_avis_location_signalement_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signalement',
            old_name='date',
            new_name='date_creation',
        ),
    ]
