# Generated by Django 4.2 on 2023-05-09 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_rename_date_signalement_date_creation'),
    ]

    operations = [
        migrations.AddField(
            model_name='objet',
            name='proprietaire',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='articles.utilisateur'),
            preserve_default=False,
        ),
    ]
