# Generated by Django 4.2 on 2023-05-09 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_objet_proprietaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='abonnement',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='articles.utilisateur'),
            preserve_default=False,
        ),
    ]
