# Generated by Django 4.2 on 2023-05-09 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_abonnement_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='avis',
            name='auteur',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='articles.utilisateur'),
            preserve_default=False,
        ),
    ]
