# Generated by Django 4.2 on 2023-05-09 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_avis_auteur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avis',
            name='auteur',
        ),
        migrations.AddField(
            model_name='location',
            name='emprunteur',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='articles.utilisateur'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='objet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='articles.objet'),
            preserve_default=False,
        ),
    ]
