# Generated by Django 4.2 on 2023-05-09 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_avis_auteur_avis_cible'),
    ]

    operations = [
        migrations.AddField(
            model_name='signalement',
            name='auteur',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='auteur_signalement', to='articles.utilisateur'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='signalement',
            name='cible',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cible_signalement', to='articles.utilisateur'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='avis',
            name='auteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auteur_avis', to='articles.utilisateur'),
        ),
        migrations.AlterField(
            model_name='avis',
            name='cible',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cible_avis', to='articles.utilisateur'),
        ),
    ]
