# Generated by Django 4.2 on 2023-05-22 09:32

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_signalement_auteur_signalement_cible_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abonnement',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='articles.utilisateur'),
        ),
        migrations.AlterField(
            model_name='location',
            name='date_debut',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2023, 5, 22)), django.core.validators.MaxValueValidator(datetime.date(2023, 8, 30))]),
        ),
        migrations.AlterField(
            model_name='location',
            name='date_fin',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2023, 5, 22)), django.core.validators.MaxValueValidator(datetime.date(2023, 8, 30))]),
        ),
    ]
