# Generated by Django 4.2 on 2023-05-24 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0015_alter_location_date_debut_alter_location_date_fin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objet',
            name='proprietaire',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='articles.utilisateur'),
        ),
    ]
