# Generated by Django 4.2 on 2023-05-25 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0019_alter_avis_auteur_alter_avis_cible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signalement',
            name='auteur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auteur_signalement', to='articles.utilisateur'),
        ),
        migrations.AlterField(
            model_name='signalement',
            name='cible',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cible_signalement', to='articles.utilisateur'),
        ),
    ]
