# Generated by Django 4.2 on 2023-05-26 09:57

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0020_alter_signalement_auteur_alter_signalement_cible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='date_debut',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2023, 5, 26)), django.core.validators.MaxValueValidator(datetime.date(2023, 9, 3))]),
        ),
        migrations.AlterField(
            model_name='location',
            name='date_fin',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2023, 5, 26)), django.core.validators.MaxValueValidator(datetime.date(2023, 9, 3))]),
        ),
    ]
